name: Android build

inputs:
  keystoreBase64:
    required: true
    description: Base64 encoded keystore

runs:
  using: 'composite'
steps:
  - name: Decode Android Keystore
    shell: bash
    run: |
      echo "${{ inputs.keystoreBase64 }}" | base64 --decode > android/app/catalog.jks

  - name: Check keystore
    shell: bash
    run: ls -l android/app/
