name: Android build

inputs:
  keystoreBase64:
    required: true
  keyPassword:
    required: true
  keyAlias:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Before Check apk
      shell: bash
      run: ls -l android/app/build/outputs/apk/release/*apk || echo "No APK yet"
    - name: Decode & Store Android Keystore
      shell: bash
      run: |
        echo "${{ inputs.keystoreBase64 }}" | base64 --decode > android/app/catalog.jks
    - name: Check keystore file
      shell: bash
      run: ls -l android/app
    - name: Build APK
      shell: bash
      run: cd android && ./gradlew assembleRelease -PkeyPassword=${{ inputs.keyPassword }} -PkeyAlias=${{ inputs.keyAlias }}
    - name: After Check apk
      shell: bash
      run: ls -l android/app/build/outputs/apk/release/*apk
