name: Android build

inputs:
  githubToken:
    required: true
  keystoreBase64:
    required: true
  keyPassword:
    required: true
  keyAlias:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Decode & Store Android Keystore
      shell: bash
      run: |
        echo "${{ inputs.keystoreBase64 }}" | base64 --decode > android/app/catalog.jks
    - name: Make gradlew executable (Grant Permission)
      shell: bash
      run: chmod +x android/gradlew
    - name: Build APK
      shell: bash
      working-directory: android
      run: ./gradlew assembleRelease -PkeyPassword=${{ inputs.keyPassword }} -PkeyAlias=${{ inputs.keyAlias }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
    - name: Download build artifacts
      uses: actions/download-artifact@v5
      with:
        name: app-release-apk
        path: ./apk
    - name: Get current versionCode
      id: get_version
      run: |
        currentVersionCode=`awk '/versionCode/ {print $2}' android/app/build.gradle`
        echo "currentVersionCode=$currentVersionCode" >> $GITHUB_OUTPUT
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: 'Android Release ${{ github.ref_name }} - ${{step.get_version.outputs.currentVersionCode}}'
        body: |
          🎉 New Android release build
          Built automatically from commit: ${{ github.sha }}
        files: ./apk/app-release.apk
        overwrite_files: true
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
    - name: Deploy
      shell: bash
      run: echo "Deploying..."
    - name: After Check apk
      shell: bash
      run: ls -l android/app/build/outputs/apk/release/*apk
