name: CI/CD for catalog app

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      android:
        type: boolean
        default: true
      ios:
        type: boolean
        default: false

jobs:
  get-code:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependency
        run: yarn install --frozen-lockfile

  dev-build:
    needs: 'get-code'
    if: ${{github.ref_name == 'mh/dev'}}
    runs-on: macos-26
    steps:
      - name: Android Build
        if: ${{inputs.android}}
        uses: ./.github/actions/android

      - name: IOS Build
        if: ${{inputs.ios}}
        uses: ./.github/actions/ios

  prod-build:
    needs: 'get-code'
    if: ${{github.ref_name == 'main'}}
    runs-on: macos-26
    steps:
      - name: Build Production
        run: echo "Prod Build"
