name: CI/CD for catalog app

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      android:
        type: boolean
        default: true
      ios:
        type: boolean
        default: false

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependency
        run: yarn install --frozen-lockfile

      - name: Android Build
        if: ${{ github.ref_name == 'mh/dev' && inputs.android}}
        uses: ./.github/actions/android
        with:
          keystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlise: ${{ secrets.ANDROID_KEY_ALIAS }}

      - name: IOS Build
        if: ${{github.ref_name == 'mh/dev' && inputs.ios}}
        uses: ./.github/actions/ios

      - name: Build Production
        if: ${{github.ref_name == 'main'}}
        run: echo "Prod Build"
