name: CI/CD for catalog app

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      android:
        type: boolean
        default: true
      ios:
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create .env file
        run: |
          echo "GOOGLE_MAPS_API_KEY=${{secrets.GOOGLE_MAPS_API_KEY}}" >> .env
          echo "API_BASE_URL=${{vars.API_BASE_URL}}" >> .env
          echo "ENV=${{vars.ENV}}" >> .env

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependency
        run: yarn install --frozen-lockfile

      - name: Android Build
        if: ${{ github.ref_name == 'mh/dev' && inputs.android}}
        uses: ./.github/actions/android
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          keystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}

      - name: IOS Build
        if: ${{github.ref_name == 'mh/dev' && inputs.ios}}
        uses: ./.github/actions/ios

      - name: Build Production
        if: ${{github.ref_name == 'main'}}
        run: echo "Prod Build"

      - name: Bump Android versionCode
        run: |
          oldVersionCode=`awk '/versionCode/ {print $2}' android/app/build.gradle`
          newVersionCode=$(($oldVersionCode + 1))
          sed -i '' 's/versionCode.*/versionCode '$newVersionCode'/' android/app/build.gradle
      - name: Commit change
        run: |
          git fetch
          git checkout ${{ github.ref_name }}
          git add android/app/build.gradle
          git commit -m "Update build number"
          git push origin ${{github.ref_name}}
